#!/usr/bin/env python3
import os
import subprocess
import argparse
import sys
import xml.etree.ElementTree as ET
from datetime import datetime

# Configuration profils for Nmap scans
SCAN_PROFILES = {
    "quick": {
        "args": "-sS -sV -sC -T4",
        "desc": "Standard quick scan (common ports), versions and default scripts."
    },
    "full": {
        "args": "-p- -sS -sU -sV -sC -A -T4",
        "desc": " Full scan (all ports), versions and OS detection."
    },
    "stealth": {
        "args": "-sS -Pn -f --data-length 32 -T2",
        "desc": " Stealth scan"
    },
    "audit": {
        "args": "-sV --script vuln,exploit,auth,discovery -T4",
        "desc": " Vulnerabilities scanner : Research of vulnerabilities with NSE scripts."
    }
}

def print_banner():
    banner = r"""
  _   _                      ____                      
 | \ | |_ __ ___   __ _ _ __/ ___|  ___ __ _ _ __      
 |  \| | '_ ` _ \ / _` | '_ \___ \ / __/ _` | '_ \     
 | |\  | | | | | | (_| | |_) |__) | (_| (_| | | | |    
 |_| \_|_| |_| |_|\__,_| .__/____/ \___\__,_|_| |_|    
                       |_|                             
    --- Port scanner ---
    """
    print(banner)

# Scan execution with Nmap
def run_nmap(target, mode):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    output_xml = f"reports/scan_{target.replace('.', '_')}_{timestamp}.xml"
    
    nmap_args = SCAN_PROFILES[mode]['args']
    nmap_cmd = f"nmap {nmap_args} -oX {output_xml} {target}"
    
    print(f"[*] Profil : {mode.upper()} | Target : {target}")
    print(f"[*] Action : {SCAN_PROFILES[mode]['desc']}")
    print(f"[*] Launching Nmap, please wait. \n")

    try:
        subprocess.run(nmap_cmd, shell=True, check=True)
        return output_xml
    except:
        sys.exit("\n Nmap error. Verified that Nmap is installed and you have the necessary permissions.")

# Construction of the Markdown report from the XML output
def build_report(xml_path, target, mode):
    md_path = xml_path.replace(".xml", ".md")
    tree = ET.parse(xml_path)
    root = tree.getroot()

    global_os = "Unknown"
    os_match = root.find(".//osmatch")
    if os_match is not None:
        global_os = os_match.get('name')

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"# Report : {target}\n\n")
        f.write(f"- **Date** : {datetime.now().strftime('%d/%m/%Y %H:%M')}\n")
        f.write(f"- **Profile used** : `{mode.upper()}`\n")
        f.write(f"- **OS detected** : `{global_os}`\n\n")
        
        # Table of ports and services
        f.write("## Port and service states\n\n")        
        f.write("| Port | Protocol | State | Service | Version | OS |\n")
        f.write("| :--- | :--- | :--- | :--- | :--- | :--- |\n")
        
        vulns_found = []

        # Extract ports information
        for port in root.findall(".//port"):
            port_id = port.get('portid')
            protocol = port.get('protocol')
            state = port.find('state').get('state')
            
            service_tag = port.find('service')
            name = service_tag.get('name', 'N/A') if service_tag is not None else "N/A"
            prod = service_tag.get('product', '') if service_tag is not None else ""
            ver = service_tag.get('version', '') if service_tag is not None else ""
            
            local_os = global_os
            if service_tag is not None and service_tag.get('ostype'):
                local_os = service_tag.get('ostype')

            f.write(f"| {port_id} | {protocol.upper()} | {state} | {name} | {prod} {ver} | {local_os} |\n")

            # Extract vulnerabilities from scripts
            for script in port.findall('script'):
                script_id = script.get('id')
                script_output = script.get('output')
                vulns_found.append((port_id, script_id, script_output))

        # Vulnerabilities Section
        if vulns_found:
            f.write("\n\n## Security analysis (Scripts NSE)\n")
            for port_id, s_id, s_out in vulns_found:
                f.write(f"\n### Port {port_id} - Script: `{s_id}`\n")
                f.write(f"```text\n{s_out.strip()}\n```\n")
        else:
            f.write("\n\n*No vulnerabilities detected*")
    
    return md_path

# Main
if __name__ == "__main__":
    print_banner()
    
    parser = argparse.ArgumentParser(description="nmap-scan : Port scanner.")
    parser.add_argument("target", help="IP or domain to scan.")
    parser.add_argument("-m", "--mode", choices=SCAN_PROFILES.keys(), default="quick", 
                        help="Mode de scan (quick, full, stealth, audit). Défaut: quick")
    
    args = parser.parse_args()
    
    # Create reports directory if not exists
    if not os.path.exists("reports"):
        os.makedirs("reports")

    # Workflow
    xml_file = run_nmap(args.target, args.mode)
    md_file = build_report(xml_file, args.target, args.mode)
    
    # Cleanup XML file
    if os.path.exists(xml_file):
        os.remove(xml_file)
    print(f"\n[+] Work done. The reports are in the file 'reports/'.")